"""empty message

Revision ID: 341f073fb71f
Revises: 5bf7616ddddd
Create Date: 2021-06-19 18:32:13.451529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341f073fb71f'
down_revision = '5bf7616ddddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shipment', sa.Column('status_updated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shipment', 'status_updated')
    # ### end Alembic commands ###
