"""empty message

Revision ID: 5bf7616ddddd
Revises: d84b0b4b0322
Create Date: 2021-06-16 20:20:56.791729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bf7616ddddd'
down_revision = 'd84b0b4b0322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'country')
    # ### end Alembic commands ###
