"""empty message

Revision ID: ad02ab3dfe97
Revises: 
Create Date: 2021-06-16 14:50:02.042371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad02ab3dfe97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shipment', sa.Column('shipping_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shipment', 'shipping_date')
    # ### end Alembic commands ###
