"""empty message

Revision ID: d84b0b4b0322
Revises: ad02ab3dfe97
Create Date: 2021-06-16 14:51:54.500702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd84b0b4b0322'
down_revision = 'ad02ab3dfe97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shipment', sa.Column('receiving_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shipment', 'receiving_date')
    # ### end Alembic commands ###
